---
api:
  geocoding:
    url: https://geocoding-api.open-meteo.com/v1/search?name={name}&count=1&format=json
  forecast:
    url: https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&forecast_days={days}&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,cloud_cover,wind_speed_10m,wind_direction_10m,wind_gusts_10m&hourly=temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation_probability,precipitation,cloud_cover,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m&timezone=GMT
    ttl: 900
  metar:
    url: https://avwx.rest/api/metar/location
    authorization:
      header: Authorization
      value: ${AVWX_API_KEY}
  nearestAirport:
    url: https://avwx.rest/api/station/near/{lat},{lon}?n=1&airport=true&format=json
    authorization:
      header: Authorization
      value: ${AVWX_API_KEY}

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      enabled: true
      legacy:
        enabled: true

springdoc:
  api-docs:
    path: /api/openapi/docs
  swagger-ui:
    path: /api/openapi/ui
